<?php

define('SOMI_MODULE_PATH', drupal_get_path('module', 'somi'));

require_once "somi.field.inc";

/**
 * Implements hook_menu.
 */
function somi_menu() {
  $items = array();
  $items['manager'] = array(
    'title' => 'Manager',
    'page callback' => 'somi_manager',
//    'theme callback' => 'ajax_base_page_theme',
//    'delivery callback' => 'ajax_deliver',
    'access callback' => TRUE,
    'description' => 'Ajax callback for view loading.',
    'type' => MENU_CALLBACK,
    'file' => 'somi.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_entity_info_alter().
 */
function somi_entity_info_alter(&$entity_info) {
  $view_modes = array(
    'user' => array(
      'teaser',
    ),
  );

  foreach ($view_modes as $key => $entity_type) {
    foreach ($entity_type as $mode) {
      $entity_info[$key]['view modes'][$mode] = array(
        'label' => t(drupal_ucfirst(str_replace('_', ' ', $mode))),
        'custom settings' => TRUE,
      );
    }
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function somi_ctools_plugin_directory($module, $plugin) {
  if (($module == 'ctools') || ($module == 'panels') || ($module == 'feeds_tamper')) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_views_api().
 */
function somi_views_api() {
  return array(
    'api' => '3.0-alpha1',
    'path' => SOMI_MODULE_PATH . '/views',
  );
}

/**
* Implements hook_ctools_plugin_api().
 */
function somi_ctools_plugin_api($owner, $api) {
  if ($owner == 'panels') {
    return array('version' => 2.0);
  }
}

